apiVersion: v1
kind: Service
metadata:
  name: {{ include "guestbook.fullname" . }}
  labels:
    {{- include "guestbook.labels" . | nindent 4 }}
spec:
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  {{- if .Values.metrics.serviceMonitor.enabled }}
    - port: 9121
      targetPort: metrics
      protocol: TCP
      name: redis-metrics
    - port: 9100
      targetPort: metrics
      protocol: TCP
      name: guestbook-metrics
  {{- end }}
  selector:
    {{- include "guestbook.selectorLabels" . | nindent 4 }}