services:
  web:
    build: .
    ports:
      - "3000:3000"
    environment:
      REDIS_HOST: redis
  redis:
    image: "redis:7"
    ports:
      - "6379:6379"
    volumes: 
      - type : volume
        source : redis-data
        target : /data

volumes:
 redis-data: