apiVersion: v2
name: guestbook
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
dependencies:
  - name: redis
    version: 22.0.7
    repository: "oci://registry-1.docker.io/bitnamicharts"
  - name: guestbook
    version: 0.1.0
    repository: "file://guestbook"