guestbook:
  replicaCount: 1

  image:
    repository: guestbook
    tag: v0.4.0

  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 10
    targetCPUUtilizationPercentage: 80
    targetMemoryUtilizationPercentage: 80

  serviceAccount:
    create: true

  podSecurityContext:
    fsGroup: 2000

  securityContext:
    capabilities:
      drop:
      - ALL
    readOnlyRootFilesystem: true
    runAsNonRoot: true
    runAsUser: 1000

  service:
    port: 3000

  resources:
    limits:
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi

  livenessProbe:
    httpGet:
      path: /healthz
      port: http
  readinessProbe:
    httpGet:
      path: /healthz
      port: http

  affinity: {}

  ingress:
    enabled: true

  metrics:
    serviceMonitor:
      enabled: true

redis:
  architecture: standalone
  auth:
    enabled: false
  master:
    persistence:
      enabled: false
    resources:
      requests:
        cpu: 100m
        memory: 64Mi
      limits:
        memory: 64Mi
  image:
    repository: redis
    tag: 8.2.1